### ISSUE TITLE
RAM corruption/timing issue? when IDE is unplugged

### ISSUE THREAD

**Issue by kikendo** [terriblefire/tf328#3]
TF328 with IDE device plugged works normally and perfectly.
When IDE device is removed, graphic corruption/lockups occur. Seems like RAM corruption or related to timing.

Unsure of which FW version I have (ask Mark/supaduper), but I have Hynix RAM chips, part#: HNY5118160B TC-60 9735A

Some tests and ways I reproduced it 100% of the times.

- AB:Tower Assault - with the IDE on, it fast blinks LEDs and reboots, never showing anything. Without, you get to see some of the game, but with corrupted graphics, until it crashes. 
- All of Amigajay and earok's CD32 releases present graphics corruption. 
- AGS: Any compilation using this menu has corrupted graphics everywhere and random lockups.
- Aladdin CD32: the intro video shows blue lines of corruption on the system without IDE. 
- Alfred Chicken: it had different crashes and graphics corruption, and one time, it went through REALLY fast through the game and then crashed.
- Arabian Nights CD32: graphics corruption and lockups.
- Pirates! Gold: Doesn't even boot.

Here are a couple of screencaps of when the graphics were corrupted:
https://i.imgur.com/mga04aK.jpg
https://i.imgur.com/0bsKZsc.jpg

One of earok's discs just failed with this error at one boot:
https://i.imgur.com/MC4AZDw.jpg
So I would check what ramlib does to see where it's failing.

**Comment by kikendo** [comment]
As discussed at EAB, turns out this is a problem with these RAM chips. They don't work.

Case closed!

**Comment by kikendo** [comment]
Sorry, have to re-open this issue.

Turns out these RAM chips are 1K so they should work.
And I thought we had it sorted :/

**Comment by MC68060** [comment]
Have 3 TF328 soldered with Hynix HY5118160BTC-60 and two with Toshiba TC5118160CFT-60.
Tested so far WB3.1, Scorched Tanks from HDD for hours... and Gloom from CD.
Worms is booting, Intro-Videos are played. But i cant find my Key-Booklet, so i come only to the code-entry.

 I'm now installing WHD-Load to test more.

**Comment by kikendo** [comment]
@MC68060 could you test in the ways described on the first post to have a common ground for testing? No test from HDD is valid as I get normal operation from IDE (hence title).
No device must be plugged to the IDE header, and try one of the above mentioned games.

Also which riser do you have to connect the boards to your CD32?

**Comment by MC68060** [comment]
I'm searching for downloads of the games.
I'm using the riser from 7-bit with the VGA-connector.

**Comment by kikendo** [comment]
Cool, since we are also suspecting the riser now, it's cool that you have another than mine (I have a kipper rev5).
I uploaded to the EAB FTP a few games to test, you can get them from there. 
ftp://ftp:any@grandis.nu/

**Comment by MC68060** [comment]
Just tested Alied Breed Tower Assault:
I can confirm your Issues, with IDE connected fast blink and reboot.
Without I can play a little, then reset.

**Comment by kikendo** [comment]
HUH! Very interesting. You are experiencing exactly the same as me meaning the riser might not be at fault.
Try Alfred Chicken if you can, it corrupts the screen very noticeably before crashing! 
Thanks for your testing! And keep us posted.

**Comment by MC68060** [comment]
Sorry... can't test Alfred Chicken.
I come to the first screen. Then it ask for pressing the red button.
Since I don't know where my Gamepad is, I can't press it.
With a Competition Pro it is not working.

**Comment by terriblefire** [comment]
So for me... if you  have deviated from the BOM you are on your own (or at least low priority). But you can leave this open as a note to others.

**Comment by terriblefire** [comment]
I ran 100 rounds of memory test with my HY5118160BTC board and no issues. 

The issues seem to be focussed around the IDE interface. 

The TF328 runs flawlessly with ISSI, Alliance and Samsung RAM. See this page. 

https://github.com/terriblefire/tf328/wiki/Verified---Tested-RAM-Chips

I wonder if the RAM is not disabling its output fast enough and its interacting badly with the IDE interface.

**Comment by terriblefire** [comment]
i see that we are using "early write" cycle. I could change this to OE controlled and that might help.

**Comment by kikendo** [comment]
MC68060, a competition pro should work, its fire button = red.

TF: thanks for looking into this, whatever it is. a  weird issue indeed.

**Comment by MC68060** [comment]
Without TF328 Alfred Chicken is also not working.
Perhaps because I burned it without Audio-Tracks?
I have only CD-Burner-XP installed, there is no Option burning an ISO with Audio.

I started the Ram-Test from Systest at 12 PM, it runs for aprox. 20h now without errors.
So perhaps really an interferance with IDE?

But I can make the Ram-Disk full and empty without problems.
Yesterday I extracted a lha of my Workbench from CD to the Ram-Disk and copied it over to the HDD.
It runs perfect.

**Comment by kikendo** [comment]
Hi @MC68060 , RAM test should not fail, that is the sneaky nature of this bug.
I also can fill u the RAM and do a RAM test with no problems, as long as IDE is connected.

As soon as IDE is disconnected, it starts to fail.

**Comment by terriblefire** [comment]
Would a version of the firmware with no Gayle support aid in diagnosis?

**Comment by kikendo** [comment]
At the moment I don't have the Xilinx programmer, maybe @MC68060 does and can test!

**Comment by terriblefire** [comment]
So for the record here. i believe you guys are using an untested jed that i gave superduper when i was very *very* drunk. I'd switch to the stock firmware for bug reporting purposes.

**Comment by kikendo** [comment]
OK I will report back when I managed to get the programmer and flashed the latest version of the firmware!

**Comment by terriblefire** [comment]
Guys, 

I dont see the issues you are seeing. I cannot support the firrmware you have installed. It was never meant to be shipped to end users. 

https://www.dropbox.com/s/mjbqd0xx33xswhl/stock_firmware.png?dl=0

**Comment by terriblefire** [comment]
The only repeatable issue i have is Superfrog ....

https://www.youtube.com/watch?v=xDmI_LJfWwM

Everything else is fine.

**Comment by MC68060** [comment]
I use the firmware downloaded here on Github :)

**Comment by terriblefire** [comment]
The issue is not repeatable here. I tried 2 different CD32 and 2 TF328s. Are the contacts clean on the edge connectors? I clean with IPA.

**Comment by terriblefire** [comment]
@MC68060 can you confirm you have a 1K resistor on R2 (next to the IDE header)?

**Comment by terriblefire** [comment]
Try this jed https://www.dropbox.com/s/fr6hwq2qdy340jd/2017_10_7_tf328_rev1_beta.zip?dl=0

It works for me perfectly.

**Comment by terriblefire** [comment]
If this issue is confirmed fixed by the above firmware i'll merge my code in and publish a set of jeds.

**Comment by terriblefire** [comment]
OK. If this is not fixed by 2017_10_8 then reopen.

**Comment by kikendo** [comment]
I cannot flash it so I can't confirm. Won't be soon til I do.

**Comment by kikendo** [comment]
Flashed new version of firmware. Issue still present/looks worse.

Screen corruption on boot screen:
https://i.imgur.com/lxH4OjV.jpg

With the previous firmware, I never had corruption on this screen.

Systest screen corrupted, and RAM test failing:
https://i.imgur.com/YdziNTx.jpg

**Comment by kikendo** [comment]
I can't reopen the issue, though?

**Comment by terriblefire** [comment]
@MC68060 are you still seeing this with the latest firmware. I have built 15 boards with all different types of RAM and not seen this

**Comment by kikendo** [comment]
But were any of those with the Hinyx RAM? I still don't trust this RAM.

**Comment by terriblefire** [comment]
Two boards with Hynix RAM. Perfect operation. The current firmware was developed for that.

**Comment by kikendo** [comment]
Well very interesting, it could be a bad batch of RAM/ Both MC68060 and me got it from the same batch from Mark. I sent a message to JOTD for him to test as we did, to see if he gets the same errors (he also got a board from that same batch).

What drives me nuts is: as long as IDE is plugged, everything runs incredibly well. So that makes me think it isn't bad RAM! But what is it, then?

**Comment by MC68060** [comment]
I have 5 Boards ready with the Firmware from Matze / Matthias. (I came also from a1k.org)
All are running well with 0 Waitstates, but I didn't test it without IDE.

@Kikendo: My Rams are from eBay, I dont know Marc?

**Comment by kikendo** [comment]
@MC68060 it's cool that you have a bunch of different boards. Please test without IDE and let us know what happens!

I tried the 0w firmware with same or worse results too, from now on I will stick to Stephen's original firmware -only-
